-- SQLite rollback recreates shipping_marks without COD fields.
CREATE TABLE shipping_marks_backup (
    id TEXT PRIMARY KEY,
    order_id TEXT NOT NULL,
    carrier_id TEXT NOT NULL,
    tracking_number TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'PENDING',
    document_type TEXT,
    document_ref TEXT,
    sender_name TEXT NOT NULL,
    sender_id TEXT NOT NULL,
    sender_id_type TEXT NOT NULL,
    sender_address TEXT NOT NULL,
    sender_city_code TEXT NOT NULL,
    sender_phone TEXT NOT NULL,
    sender_email TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_id TEXT NOT NULL,
    recipient_id_type TEXT NOT NULL,
    recipient_address TEXT NOT NULL,
    recipient_city_code TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    recipient_email TEXT NOT NULL,
    total_weight REAL NOT NULL DEFAULT 0,
    total_volumetric_weight REAL NOT NULL DEFAULT 0,
    declared_value REAL NOT NULL DEFAULT 0,
    payment_form TEXT NOT NULL DEFAULT '',
    observations TEXT,
    dispatch_batch_id TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dispatch_batch_id) REFERENCES dispatch_batches(id) ON DELETE SET NULL
);

INSERT INTO shipping_marks_backup (
    id,
    order_id,
    carrier_id,
    tracking_number,
    status,
    document_type,
    document_ref,
    sender_name,
    sender_id,
    sender_id_type,
    sender_address,
    sender_city_code,
    sender_phone,
    sender_email,
    recipient_name,
    recipient_id,
    recipient_id_type,
    recipient_address,
    recipient_city_code,
    recipient_phone,
    recipient_email,
    total_weight,
    total_volumetric_weight,
    declared_value,
    payment_form,
    observations,
    dispatch_batch_id,
    created_at,
    updated_at
)
SELECT
    id,
    order_id,
    carrier_id,
    tracking_number,
    status,
    document_type,
    document_ref,
    sender_name,
    sender_id,
    sender_id_type,
    sender_address,
    sender_city_code,
    sender_phone,
    sender_email,
    recipient_name,
    recipient_id,
    recipient_id_type,
    recipient_address,
    recipient_city_code,
    recipient_phone,
    recipient_email,
    total_weight,
    total_volumetric_weight,
    declared_value,
    payment_form,
    observations,
    dispatch_batch_id,
    created_at,
    updated_at
FROM shipping_marks;

DROP TABLE shipping_marks;
ALTER TABLE shipping_marks_backup RENAME TO shipping_marks;
CREATE INDEX idx_shipping_marks_order_id ON shipping_marks(order_id);
CREATE INDEX idx_shipping_marks_carrier_id ON shipping_marks(carrier_id);
CREATE INDEX idx_shipping_marks_dispatch_batch_id ON shipping_marks(dispatch_batch_id);
