server {
    listen 3001;
    root /usr/share/nginx/html;

    location = /wiki {
        return 301 /wiki/;
    }

    location /wiki/ {
        try_files $uri $uri.html $uri/index.html =404;
    }
}
